### ISSUE TITLE
Publish updated version to pub.dev

### ISSUE THREAD

**Issue by savy-91** [taodo2291/xgesture_flutter#13]
Hi! Would it be possible for you to release a new version of the library to pub.dev?

It seems like the master branch here has new commits, among which for example one that enables the user of the library to set the `behavior` to `translucent` whereas the version on `pub.dev` is stuck at the commit when null-safety was added.

**Comment by taodo2291** [comment]
Hi Saverio Murgia,

I have just released a new version. Please check it out:
https://pub.dev/packages/gesture_x_detector/versions/1.1.0
