### ISSUE TITLE
Support for scaling by scrolling the mouse wheel

### ISSUE THREAD

**Issue by DrStefanFriedrich** [taodo2291/xgesture_flutter#14]
Right now scaling is only supported by the two finger gesture.

Are there any plans to support scaling by scrolling the mouse wheel?

If Flutter Web is used, it is likely that the user does not have a touch screen, but is using a mouse instead.

I think an `onPointerSignal` must be implemented, something like this:

```
  void onPointerSignal(PointerSignalEvent event) {
    if (event is PointerScrollEvent) {
      // Use event.scrollDelta.distance in some way...
    }
  }
```

Of course, when scaling with the mouse wheel, the rotation angle is always 0.

**Comment by taodo2291** [comment]
Hi Dr. Stefan Friedrich,

Thank you for your suggestion. Could you please submit a PR for that? I'll review and release it soon.

**Comment by DrStefanFriedrich** [comment]
Sorry @taodo2291, maybe a misunderstanding. It was just a question, I have no PR.

I just realized that it probably can be done using `onPointerSignal`. It was just an idea. I did no coding so far.

**Comment by DrStefanFriedrich** [comment]
Hi @taodo2291, how are you? Did you find some time and could take a look?

**Comment by taodo2291** [comment]
Hi @DrStefanFriedrich ,

I have taken a look at your suggestion. But have no time to implement it yet. 

Yes, that can be can be done by using onPointerSignal. But it's better to make the user decide which behavior they would like when the mouse wheel scroll (scaling or just scrolling). I suggest we should support both behaviors and let the user decide which one they need.

something like: mouseWheelBehavior: MouseWheelBehavior.Scale || MouseWheelBehavior.Scroll

I'm planning to implement a new version for this package that supports multiple touches this weekend and will implement your suggestion also. Hope I can finish everything this weekend. 

If this is an urgent case, please raise a PR, I'll review and release it soon.

**Comment by taodo2291** [comment]
The user will decide what to do when the scrolling event occurs. 
Scroll event data: 
```
{
     localPos,    // can use this as the focal point in case the user uses this event for scale, rotate
     position,    
     scrollDelta   // the delta Offset, use scrollDelta.distance for scale, rotate. Or just scrollDelta for scroll
}
```

PR: https://github.com/taodo2291/xgesture_flutter/pull/17

**Comment by DrStefanFriedrich** [comment]
Perfect, works like a charm!
