### ISSUE TITLE
 Invalid value: Only valid value is 0: 1. Error thrown null.

### ISSUE THREAD

**Issue by neelansh-creatorstack** [taodo2291/xgesture_flutter#15]
Happening after upgrading to 1.0.0

Non-fatal Exception: FlutterError
0  ???                            0x0 State.widget (framework.dart)
1  ???                            0x0 _XGestureDetectorState.onPointerMove + 180 (gesture_x_detector.dart:180)
2  ???                            0x0 RenderPointerListener.handleEvent + 2892 (proxy_box.dart:2892)
3  ???                            0x0 GestureBinding.dispatchEvent + 419 (binding.dart:419)
4  ???                            0x0 RendererBinding.dispatchEvent + 322 (binding.dart:322)
5  ???                            0x0 GestureBinding._handlePointerEventImmediately + 374 (binding.dart:374)
6  ???                            0x0 GestureBinding.handlePointerEvent + 338 (binding.dart:338)
7  ???                            0x0 GestureBinding._flushPointerEventQueue + 296 (binding.dart:296)
8  ???                            0x0 GestureBinding._handlePointerDataPacket + 279 (binding.dart:279)

**Comment by taodo2291** [comment]
Did you mean version 1.1.0 ?. Please downgrade to version 1.0.0 first.  I'll check and fix it later.

**Comment by neelansh-creatorstack** [comment]
Yes 1.1.0

**Comment by taodo2291** [comment]
New version: https://pub.dev/packages/gesture_x_detector/versions/1.1.1

Please let me know if it solved this issue.
