### ISSUE TITLE
can implement longPressEnd?

### ISSUE THREAD

**Issue by bhanuka96** [taodo2291/xgesture_flutter#3]
Is it possible to implement longPressEnd event?

**Comment by taodo2291** [comment]
If you mean the event when the user releases the finger after the long-press event then Yes, it is possible.

I'll make a new release soon.

**Comment by bhanuka96** [comment]
@taodo2291 yes. Thanks. `LongPressStart` and `LongPressEnd` events. Thank you. I am currently using something like this.

```
XGestureDetector(
            onMoveUpdate: (details) {
              // code
            },
            onMoveEnd: (d) {
              // code
            },
            child: GestureDetector(
              onTap: (){
                // code
              },
              onLongPressStart: (d){
               // code
              },
              onLongPressEnd: (d) {
               // code
              },
              child: AnimatedContainer(...
```

**Comment by taodo2291** [comment]
Checkout new version which includes onLongPressEnd: [gesture_x_detector 1.0.0-nullsafety.1](https://pub.dev/packages/gesture_x_detector/versions/1.0.0-nullsafety.1)
